# Generated by Django 5.2.1 on 2025-05-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2000, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('scrape_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='api_link_url_2d21a9_idx'), models.Index(fields=['domain'], name='api_link_domain_642ef8_idx'), models.Index(fields=['is_active', 'created_at'], name='api_link_is_acti_126286_idx')],
            },
        ),
        migrations.CreateModel(
            name='SerpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('read_more_link', models.URLField(blank=True, max_length=2000)),
                ('language', models.CharField(default='en', max_length=10)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('top_image', models.URLField(blank=True, max_length=1000)),
                ('meta_img', models.URLField(blank=True, max_length=1000)),
                ('images', models.JSONField(blank=True, default=list)),
                ('movies', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('meta_keywords', models.JSONField(blank=True, default=list)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_lang', models.CharField(blank=True, max_length=10)),
                ('meta_favicon', models.URLField(blank=True, max_length=1000)),
                ('meta_site_name', models.CharField(blank=True, max_length=255)),
                ('canonical_link', models.URLField(blank=True, max_length=2000)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serp_content', to='api.link')),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='api_serpcon_url_084629_idx'), models.Index(fields=['language'], name='api_serpcon_languag_616d89_idx'), models.Index(fields=['publish_date'], name='api_serpcon_publish_daa04b_idx'), models.Index(fields=['created_at'], name='api_serpcon_created_4e450f_idx')],
            },
        ),
    ]
