# Generated by Django 5.2.1 on 2025-05-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link_serpcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HtmlContentUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('html_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.htmlcontent')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.link')),
            ],
        ),
        migrations.AddField(
            model_name='htmlcontent',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='html_contents', through='api.HtmlContentUrl', to='api.link'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.fact')),
            ],
        ),
        migrations.AddField(
            model_name='htmlcontent',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_content', to='api.question'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddIndex(
            model_name='htmlcontenturl',
            index=models.Index(fields=['link'], name='api_htmlcon_link_id_6222c5_idx'),
        ),
    ]
