# Generated by Django 5.2.1 on 2025-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_htmlcontent_htmlcontenturl_htmlcontent_urls_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_fetchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=512),
        ),
    ]
