# Generated by Django 5.2.1 on 2025-05-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_is_fetchable_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='questions_data',
        ),
    ]
